version: "3.9"
services:
  cont:
    image: sshlibrary:latest
    volumes:
        - type: bind
          source: ./results
          target: /SSHLibrary/atest/results  
    command: /bin/bash -c "service ssh start && cd SSHLibrary && git checkout master && git pull origin master && python3 atest/run.py ."
    
  
    
